pipeline {
    agent any
    
    environment {
        registryName = "taskdevacr.azurecr.io/taskdevacr:latest"
        registryUrl = "taskdevacr.azurecr.io"
        registryCredential = "ACR"
        dockerImage = ''
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/ahiazd/task_2bcloud.git']])
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build(registryName)
                }
            }
        }
        
         stage('Upload Image to ACR') {
           steps{   
              script {
            docker.withRegistry( "http://${registryUrl}", registryCredential ) {
            dockerImage.push()
            }
          }
        }
     }
    }
}
